version: "3.8"

services:
  app:
    build: .
    container_name: cccat15_app
    environment:
      - .env
    env_file:
      - .env

    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/application
    depends_on: [ 'redis', 'db' ]
    networks:
      - cccat15

  db:
    build:
      context: ./.docker/mysql
      dockerfile: Dockerfile
    container_name: cccat15_db
    restart: always
    tty: true
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql:rw
      - ./.docker/mysql/scripts:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - cccat15

  redis:
    image: redis:alpine
    container_name: cccat15_redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - cccat15

  rabbit:
    image: "rabbitmq:3-management"
    container_name: cccat15_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./.docker/rabbitmq/rabbitmq_data:/var/lib/rabbitmq
    #            - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - cccat15

networks:
  cccat15:
    driver: bridge
